name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:

jobs:
  cmake-example:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt install -y gfortran python3-dev libomp-15-dev lcov intel-mkl
      - name: Cache Crates
        uses: actions/cache@v4
        with:
          path: |
            ./build
          key: cmake-${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            cmake-${{ runner.os }}
            cmake
      - name: Run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./vsag-cmake-example
