name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:

jobs:
  test-vendor:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
